modLoader="javafml"
loaderVersion="[35,)"
license="${license}"
issueTrackerURL="${issue_tracker}"
[[mods]]
    modId="aerobaticelytrajetpack"
    version="${version}"
    displayName="${display}"
    updateJSONURL="${update_json}"
    displayURL="${page}"
    logoFile="${logo_file}"
    credits="${credits}"
    authors="${authors}"
    description='''${description}'''
[[dependencies.aerobaticelytrajetpack]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytrajetpack]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytrajetpack]]
    modId="aerobaticelytra"
    mandatory=true
    versionRange="[1.0,2.0)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.aerobaticelytrajetpack]]
    modId="lazulib"
    versionRange="[1.0,2.0)"
    mandatory=true
    ordering="NONE"
    side="BOTH"
[[dependencies.aerobaticelytrajetpack]]
    modId="simpleconfig"
    versionRange="[1.0,2.0)"
    mandatory=true
    ordering="NONE"
    side="BOTH"